channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # base
  - r-base =3.6.1
  - python >=3.7
  # render notebooks
  - grst::reportsrender >=0.2.1
  # run notebook interactively in jupyter notebook
  - ipykernel >=5.1.2
  # for the notebooks
  - matplotlib
  - pandas
  - pip:
      - reportsrender >=0.3.0


